# Site settings
title: Jonas Kaufman
header-img: img/home-bg.jpg
email: jonas.l.kaufman@gmail.com
description: "The personal website of Jonas Kaufman"
baseurl: ""
url: "http://jonaskaufman.com"
twitter_username:
github_username:  jonaskaufman
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["404.html", "less","node_modules","Gruntfile.js","package.json","README.md"]
